---
language: ruby
bundler_args: --without development
script: "bundle exec rake validate lint spec SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 2.7"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.7"
notifications:
  email: false
gemfile: .gemfile

