language: ruby
script: "rake rspec smoke lint"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.7.0"
matrix:
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.1.0
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 3.2.0"
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 3.4.0"
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 3.7.0"
gemfile: .gemfile

